### ISSUE TITLE
Enabling Node Integration

### ISSUE THREAD

**Issue by leumasme** [fuzzc0re/electron-svelte-typescript#13]
I'm trying to enable node:fs in the frontend part of a project that I started using your template.
Actually enabling nodeIntegration was easy enough, by just changing config arguments passed to the BrowserWindow, but I am unable to get rollup to properly transpile my imports to inbuilt libraries.

After the config changes, require() works fine in the electron browser console, but using `import fs from "fs"` fails with rollup warnings that it's unable to locate global variables for that library, and the import is simply gone in the compiled bundle.js, instead assuming that fs is available as a global variable.

I've tried changing the `browser` option of `@rollup/plugin-node-resolve` to false, but that did not help.
I have also created [a Stackoverflow question](https://stackoverflow.com/questions/72176274/preserving-node-js-built-in-imports-for-electron-in-rollup) about this 2 days ago, but not gotten any responses.

I would appreciate it if you could help me resolve this so that I am able to use node libraries (not just polyfills) in the frontend. (You could also make a branch for it on the template repo, so people can create a project from the template in whichever configuration they wish)

Thanks for your time!

**Comment by SilentEchoUK** [comment]
I don't know of a way to do that but there are packages like this one that have mapped the Browser File System API to the `fs` API: https://www.npmjs.com/package/browser-fs-access

**Comment by leumasme** [comment]
The deciding factor that caused rollup to compile without imports was the `output.format` config of rollup.config.js.
Setting this to `cjs` persists unknown imports, allowing use of node modules if NodeIntegration is enabled.

**Comment by fuzzc0re** [comment]
I would use [ipc messaging](https://www.electronjs.org/docs/latest/tutorial/ipc) to achieve whatever you want to do with 'fs' in the browser because of [this security recommendation from Electron](https://www.electronjs.org/docs/latest/tutorial/security#2-do-not-enable-nodejs-integration-for-remote-content).
