### ISSUE TITLE
Is it possible to add ipcRenderer to frondend main.ts?

### ISSUE THREAD

**Issue by gantrol** [fuzzc0re/electron-svelte-typescript#7]
It seems that frontend just svelte frontend files, and I have no idea with adding ipcRenderer for main.ts. Would you help me?

**Comment by fuzzc0re** [comment]
It's been a while since I was doing electron dev work. I am sure that you can find a tutorial that can answer your question.
Bear in mind that for ipcRenderer to do anything, you need a correspoding ipcMain in electron to handle the message.

Cheers.
